import { Property } from '@/types/database';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    registered_by_id: 'user-1',
    title: 'Apartamento Vita Residencial',
    description: 'Apartamento de luxo com vista panorâmica, 3 suítes e área de lazer completa.',
    type: 'Apartamento',
    transaction_type: 'sale',
    property_category: 'residential',
    price: 1850000,
    area_total: 140,
    area_useful: 120,
    rooms: 3,
    suites: 3,
    bathrooms: 4,
    parking_spaces: 2,
    pattern: 'high_end',
    status: 'available',
    is_highlight: true,
    images: [],
    commission_estimated_percent: 2.5,
    address_street: 'Rua das Flores, 123',
    address_city: 'São Paulo',
    address_state: 'SP',
    metadata: {
      rooms: 3,
      bathrooms: 4,
      area: 120,
      parking: 2,
      features: ['Piscina', 'Academia', 'Churrasqueira']
    },
    created_at: new Date().toISOString()
  },
  {
    id: 'prop-2',
    registered_by_id: 'user-1',
    title: 'Studio Moderno Pinheiros',
    description: 'Studio ideal para investimento ou moradia, próximo ao metrô.',
    type: 'Studio',
    transaction_type: 'sale',
    property_category: 'residential',
    price: 480000,
    area_total: 35,
    area_useful: 35,
    rooms: 1,
    suites: 0,
    bathrooms: 1,
    parking_spaces: 0,
    pattern: 'medium',
    status: 'available',
    is_highlight: false,
    images: [],
    commission_estimated_percent: 5.0,
    address_street: 'Av. Rebouças, 500',
    address_city: 'São Paulo',
    address_state: 'SP',
    metadata: {
      rooms: 1,
      bathrooms: 1,
      area: 35,
      parking: 0,
      features: ['Mobiliado', 'Coworking']
    },
    created_at: new Date().toISOString()
  },
  {
    id: 'prop-3',
    registered_by_id: 'user-1',
    title: 'Cobertura Duplex Leblon',
    description: 'Exclusiva cobertura com piscina privativa e vista mar definitiva.',
    type: 'Cobertura',
    transaction_type: 'sale',
    property_category: 'residential',
    price: 12500000,
    area_total: 400,
    area_useful: 350,
    rooms: 4,
    suites: 4,
    bathrooms: 6,
    parking_spaces: 4,
    pattern: 'high_end',
    status: 'reserved',
    is_highlight: true,
    images: [],
    commission_estimated_percent: 3.0,
    address_street: 'Av. Delfim Moreira, 1000',
    address_city: 'Rio de Janeiro',
    address_state: 'RJ',
    metadata: {
      rooms: 4,
      bathrooms: 6,
      area: 350,
      parking: 4,
      features: ['Vista Mar', 'Piscina Privativa', 'Automação']
    },
    created_at: new Date().toISOString()
  }
];
